language: php
php:
  - 7.3
  - 7.2
  - nightly

before_script:
  - composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/php-coveralls -v

matrix:
  allow_failures:
    - php: nightly
