#!/usr/bin/php
<?php

/**
 * Command-line wrapper-interface for rah_plugcompiler
 *
 * @package rah_plugcompiler
 * @author Jukka Svahn
 * @copyright (c) 2011 Jukka Svahn
 * @license GNU GPLv2
 * @link https://github.com/gocom/MassPlugCompiler
 *
 * Copyright (c) 2011 Jukka Svahn <http://rahforum.biz>
 * Licensed under GNU Genral Public License version 2
 * http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Requires PHP 5.2.0
 */

while(1) {

	if($argc <= 1) {
		echo "Source directory:\n";
		$handle = fopen('php://stdin', 'r');
		$path = trim(fgets($handle));
	}

	else {
		$path = $argv[1];
	}

	if(empty($path)) {
		$path = dirname(__FILE__);
	}
	
	if(
		!file_exists($path) || 
		!is_dir($path) || 
		!is_readable($path)
	) {
		echo "Is not valid directory\n";
		exit;
	}
	
	$rundir = dirname(__FILE__);

	include $rundir . '/rah_plugcompile.php';
	
	$cache = $rundir . '/packages';
	
	if(!empty($argv[2])) {
		$cache = $argv[2];
	}
	
	elseif(!file_exists($cache)) {
		mkdir($cache);
	}

	rah_plugcompile::instance()
		->set('cache', $cache);

	echo rah_plugcompile::instance()
		->set('source', $path)
		->package()
		->get();
	
	rah_plugcompile::instance()
		->write();
}

exit;

?>